version: '3.8'

services:
  servicea:
    build:
      context: .  # The root of your repository
      dockerfile: servicea/Dockerfile  # Path to the Dockerfile for servicea
    container_name: servicea
    ports:
      - "8001:8001"
    networks:
      - app-network

  serviceb:
    build:
      context: .  # The root of your repository
      dockerfile: serviceb/Dockerfile  # Path to the Dockerfile for serviceb
    container_name: serviceb
    ports:
      - "8002:8002"
    networks:
      - app-network

  servicec:
    build:
      context: .  # The root of your repository
      dockerfile: servicec/Dockerfile  # Path to the Dockerfile for servicec
    container_name: servicec
    ports:
      - "8003:8003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
